"""empty message

Revision ID: fd9def0a6eab
Revises: ffdc0a98111c
Create Date: 2022-07-06 16:28:26.788164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9def0a6eab'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'biography')
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
