"""empty message

Revision ID: 50f7ae0ea621
Revises: dd049d94469c
Create Date: 2022-07-07 16:25:49.477304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f7ae0ea621'
down_revision = 'dd049d94469c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bunnies', sa.Column('sex', sa.String(length=6), nullable=False))
    op.add_column('bunnies', sa.Column('breed', sa.String(length=50), nullable=False))
    op.drop_column('bunnies', 'color')
    op.drop_column('bunnies', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bunnies', sa.Column('gender', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.add_column('bunnies', sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('bunnies', 'breed')
    op.drop_column('bunnies', 'sex')
    # ### end Alembic commands ###
